version: '3.8'

services:
    file-converter-api:
        image: file-converter
        restart: always
        ports:
            - "3000:3000"
        environment:
            - "NODE_ENV=production"
        